#!/usr/bin/env bash
# Stage 4: Choose & Wire Sub-Agents + Providers
set -euo pipefail

source "$(dirname "$0")/lib/common.sh"

guard_step 4

info "=== Stage 4: Agent Wiring ==="

require_file "setup_answers.yaml"

# ------------------------------------------------------------------
# Read config
# ------------------------------------------------------------------
ENABLED_AGENTS=$(python3 -c "
import yaml
with open('setup_answers.yaml') as f:
    data = yaml.safe_load(f)
for agent in data.get('agents', {}).get('enabled', []):
    print(agent)
")

PROVIDER_MODE=$(python3 -c "
import yaml
with open('setup_answers.yaml') as f:
    data = yaml.safe_load(f)
print(data.get('providers', {}).get('mode', 'api-keys'))
")

info "Enabled agents: $ENABLED_AGENTS"
info "Provider mode: $PROVIDER_MODE"

# ------------------------------------------------------------------
# Create .env from template
# ------------------------------------------------------------------
if [[ ! -f ".env.example" ]]; then
    die ".env.example not found. Cannot create .env."
fi

cp .env.example .env

# Fill in keys from setup_answers.yaml
python3 << 'PYEOF'
import yaml, re

with open('setup_answers.yaml') as f:
    config = yaml.safe_load(f)

with open('.env') as f:
    env = f.read()

provider_mode = config.get('providers', {}).get('mode', 'api-keys')

# Set PROXY_MODE
env = re.sub(r'^PROXY_MODE=.*$', f'PROXY_MODE={"true" if provider_mode == "cli-proxy" else "false"}', env, flags=re.MULTILINE)

if provider_mode == 'api-keys':
    # Direct API keys mode
    providers = config.get('providers', {})
    mappings = {
        'anthropic': 'ANTHROPIC_API_KEY',
        'google': 'GOOGLE_API_KEY',
        'kimi': 'KIMI_API_KEY',
        'openrouter': 'OPENROUTER_API_KEY',
        'openai': 'OPENAI_API_KEY',
    }

    for provider, env_var in mappings.items():
        key = providers.get(provider, {}).get('api_key', '')
        if key:
            env = re.sub(rf'^{env_var}=.*$', f'{env_var}={key}', env, flags=re.MULTILINE)

elif provider_mode == 'cli-proxy':
    # CLI proxy mode — configure proxy ports
    cli_proxy = config.get('providers', {}).get('cli_proxy', {})
    enabled_proxies = cli_proxy.get('enabled', [])
    ports = cli_proxy.get('ports', {})

    if 'claude' in enabled_proxies:
        port = ports.get('claude', 3456)
        env = re.sub(r'^CLAUDE_PROXY_URL=.*$', f'CLAUDE_PROXY_URL=http://127.0.0.1:{port}/v1', env, flags=re.MULTILINE)

    if 'gemini' in enabled_proxies:
        port = ports.get('gemini', 3457)
        env = re.sub(r'^GEMINI_PROXY_URL=.*$', f'GEMINI_PROXY_URL=http://127.0.0.1:{port}/v1', env, flags=re.MULTILINE)

# Paths
vault = config.get('paths', {}).get('vault', '')
hermes_home = config.get('paths', {}).get('hermes_home', '')
if vault:
    env = re.sub(r'^VAULT_PATH=.*$', f'VAULT_PATH={vault}', env, flags=re.MULTILINE)
if hermes_home:
    env = re.sub(r'^HERMES_HOME=.*$', f'HERMES_HOME={hermes_home}', env, flags=re.MULTILINE)

# Delivery
if config.get('delivery', {}).get('platform') == 'telegram':
    tg = config.get('delivery', {}).get('telegram', {})
    bot_token = tg.get('bot_token', '')
    chat_id = tg.get('chat_id', '')
    if bot_token:
        env = re.sub(r'^TELEGRAM_BOT_TOKEN_HERMES=.*$', f'TELEGRAM_BOT_TOKEN_HERMES={bot_token}', env, flags=re.MULTILINE)
    if chat_id:
        env = re.sub(r'^TELEGRAM_CHAT_ID=.*$', f'TELEGRAM_CHAT_ID={chat_id}', env, flags=re.MULTILINE)

with open('.env', 'w') as f:
    f.write(env)
PYEOF

chmod 600 .env
info ".env created with permissions 600"

# Ensure .env is in .gitignore
if ! grep -q "^\.env$" .gitignore 2>/dev/null; then
    echo ".env" >> .gitignore
    info "Added .env to .gitignore"
fi

# ------------------------------------------------------------------
# Write AGENT_ROSTER.md to vault
# ------------------------------------------------------------------
VAULT_PATH=$(read_yaml_key setup_answers.yaml "paths.vault" || echo "$HOME/Documents/Home-Brain")
VAULT_PATH="${VAULT_PATH/#\~/$HOME}"

mkdir -p "$VAULT_PATH"

cat > "$VAULT_PATH/AGENT_ROSTER.md" << EOF
# Agent Roster

*Auto-generated by Hermes Setup Kit. Edit with care.*

| Agent | Role | Provider | Model | Status |
|-------|------|----------|-------|--------|
EOF

python3 << 'PYEOF'
import yaml

with open('setup_answers.yaml') as f:
    config = yaml.safe_load(f)

enabled = config.get('agents', {}).get('enabled', [])
roster = config.get('agents', {}).get('roster', {})
provider_mode = config.get('providers', {}).get('mode', 'api-keys')

with open("""$VAULT_PATH""" + '/AGENT_ROSTER.md', 'a') as f:
    for agent_id in enabled:
        info = roster.get(agent_id, {})
        name = info.get('name', agent_id.title())
        provider = info.get('provider', 'unknown')
        model = info.get('model', 'unknown')
        # Add proxy note if applicable
        note = ""
        if provider_mode == 'cli-proxy':
            if provider in ('anthropic', 'claude'):
                note = " (via proxy)"
            elif provider in ('google', 'gemini'):
                note = " (via proxy)"
        f.write(f"| {name} | {agent_id} | {provider}{note} | {model} | active |\n")
PYEOF

info "AGENT_ROSTER.md written to vault"

set_step 4
info "=== Stage 4 complete ==="
