#!/usr/bin/env bash
# Stage 6: Configure Delivery (Telegram, Slack, or local-only)
set -euo pipefail

source "$(dirname "$0")/lib/common.sh"

guard_step 6

info "=== Stage 6: Delivery Configuration ==="

require_answers_v2 "setup_answers.yaml"

HERMES_HOME=$(read_yaml_key setup_answers.yaml "paths.hermes_home" || echo "$HOME/.hermes")
HERMES_HOME="${HERMES_HOME/#\~/$HOME}"

PLATFORM=$(read_yaml_key setup_answers.yaml "delivery.platform" || echo "local-only")

info "Delivery platform: $PLATFORM"

# Ensure profiles directory exists
mkdir -p "$HERMES_HOME/profiles"

# ------------------------------------------------------------------
# Telegram
# ------------------------------------------------------------------
if [[ "$PLATFORM" == "telegram" ]]; then
    info "Configuring Telegram delivery..."

    CHAT_ID=$(read_yaml_key setup_answers.yaml "delivery.telegram.chat_id" || echo "")

    # One bot token per squad agent (delivery.telegram.bot_tokens.<agent>);
    # legacy single delivery.telegram.bot_token maps to hermes.
    AGENTS="hermes hephaestus clio talaria"
    ANY_TOKEN=""

    {
        echo "# Telegram Bot Configuration"
        echo "# Auto-generated by Hermes Setup Kit"
        echo "platform: telegram"
        echo "chat_id: \"$CHAT_ID\""
        echo "bot_tokens:"
    } > "$HERMES_HOME/profiles/telegram.yaml"

    for agent in $AGENTS; do
        TOKEN=$(read_yaml_key setup_answers.yaml "delivery.telegram.bot_tokens.$agent" || echo "")
        if [[ -z "$TOKEN" && "$agent" == "hermes" ]]; then
            TOKEN=$(read_yaml_key setup_answers.yaml "delivery.telegram.bot_token" || echo "")
        fi
        if [[ -n "$TOKEN" ]]; then
            echo "  $agent: \"$TOKEN\"" >> "$HERMES_HOME/profiles/telegram.yaml"
            ANY_TOKEN="$TOKEN"

            # Validate each token via Telegram API
            if curl -s "https://api.telegram.org/bot${TOKEN}/getMe" | grep -q '"ok":true'; then
                info "Telegram Bot API validation ($agent): PASS"
            else
                warn "Telegram Bot API validation ($agent): FAIL (token may be invalid or network issue)"
            fi
        fi
    done

    if [[ -z "$ANY_TOKEN" ]]; then
        warn "Telegram platform selected but no bot tokens found in setup_answers.yaml"
        rm -f "$HERMES_HOME/profiles/telegram.yaml"
    else
        chmod 600 "$HERMES_HOME/profiles/telegram.yaml"
        info "Wrote $HERMES_HOME/profiles/telegram.yaml"
    fi
fi

# ------------------------------------------------------------------
# Slack
# ------------------------------------------------------------------
if [[ "$PLATFORM" == "slack" ]]; then
    info "Configuring Slack delivery..."

    WEBHOOK_URL=$(read_yaml_key setup_answers.yaml "delivery.slack.webhook_url" || echo "")
    CHANNEL=$(read_yaml_key setup_answers.yaml "delivery.slack.channel" || echo "")

    if [[ -z "$WEBHOOK_URL" ]]; then
        warn "Slack platform selected but no webhook_url found in setup_answers.yaml"
    else
        cat > "$HERMES_HOME/profiles/slack.yaml" << EOF
# Slack Webhook Configuration
# Auto-generated by Hermes Setup Kit
platform: slack
webhook_url: "$WEBHOOK_URL"
channel: "$CHANNEL"
EOF
        chmod 600 "$HERMES_HOME/profiles/slack.yaml"
        info "Wrote $HERMES_HOME/profiles/slack.yaml"
    fi
fi

# ------------------------------------------------------------------
# local-only / none: nothing to do
# ------------------------------------------------------------------
if [[ "$PLATFORM" == "local-only" || "$PLATFORM" == "none" ]]; then
    info "Delivery is local-only. No external profiles needed."
fi

set_step 6
info "=== Stage 6 complete ==="
