#!/usr/bin/env bash
# Stage 6: Configure Delivery (Telegram, Slack, or local-only)
set -euo pipefail

source "$(dirname "$0")/lib/common.sh"

guard_step 6

info "=== Stage 6: Delivery Configuration ==="

require_file "setup_answers.yaml"

HERMES_HOME=$(read_yaml_key setup_answers.yaml "paths.hermes_home" || echo "$HOME/.hermes")
HERMES_HOME="${HERMES_HOME/#\~/$HOME}"

PLATFORM=$(read_yaml_key setup_answers.yaml "delivery.platform" || echo "local-only")

info "Delivery platform: $PLATFORM"

# Ensure profiles directory exists
mkdir -p "$HERMES_HOME/profiles"

# ------------------------------------------------------------------
# Telegram
# ------------------------------------------------------------------
if [[ "$PLATFORM" == "telegram" ]]; then
    info "Configuring Telegram delivery..."

    BOT_TOKEN=$(read_yaml_key setup_answers.yaml "delivery.telegram.bot_token" || echo "")
    CHAT_ID=$(read_yaml_key setup_answers.yaml "delivery.telegram.chat_id" || echo "")

    if [[ -z "$BOT_TOKEN" ]]; then
        warn "Telegram platform selected but no bot_token found in setup_answers.yaml"
    else
        cat > "$HERMES_HOME/profiles/telegram.yaml" << EOF
# Telegram Bot Configuration
# Auto-generated by Hermes Setup Kit
platform: telegram
bot_token: "$BOT_TOKEN"
chat_id: "$CHAT_ID"
EOF
        chmod 600 "$HERMES_HOME/profiles/telegram.yaml"
        info "Wrote $HERMES_HOME/profiles/telegram.yaml"
    fi

    # Validate bot token via Telegram API
    if [[ -n "$BOT_TOKEN" ]]; then
        if curl -s "https://api.telegram.org/bot${BOT_TOKEN}/getMe" | grep -q '"ok":true'; then
            info "Telegram Bot API validation: PASS"
        else
            warn "Telegram Bot API validation: FAIL (token may be invalid or network issue)"
        fi
    fi
fi

# ------------------------------------------------------------------
# Slack
# ------------------------------------------------------------------
if [[ "$PLATFORM" == "slack" ]]; then
    info "Configuring Slack delivery..."

    WEBHOOK_URL=$(read_yaml_key setup_answers.yaml "delivery.slack.webhook_url" || echo "")
    CHANNEL=$(read_yaml_key setup_answers.yaml "delivery.slack.channel" || echo "")

    if [[ -z "$WEBHOOK_URL" ]]; then
        warn "Slack platform selected but no webhook_url found in setup_answers.yaml"
    else
        cat > "$HERMES_HOME/profiles/slack.yaml" << EOF
# Slack Webhook Configuration
# Auto-generated by Hermes Setup Kit
platform: slack
webhook_url: "$WEBHOOK_URL"
channel: "$CHANNEL"
EOF
        chmod 600 "$HERMES_HOME/profiles/slack.yaml"
        info "Wrote $HERMES_HOME/profiles/slack.yaml"
    fi
fi

# ------------------------------------------------------------------
# local-only / none: nothing to do
# ------------------------------------------------------------------
if [[ "$PLATFORM" == "local-only" || "$PLATFORM" == "none" ]]; then
    info "Delivery is local-only. No external profiles needed."
fi

set_step 6
info "=== Stage 6 complete ==="
